### ISSUE TITLE
2nd and 3rd uniques for for VividVale :)

### ISSUE THREAD

**Issue by BennieCUBED** [Caballero-Arepa/Community-Civs#101]
2nd UU: Fire Archer which replaces the Composite Archer, No movement cost when pillaging 

2nd UB: Star Gazing spot which replaces the Amphitheater, 1+ or 2+ Happiness for every 5 population.

**Comment by Caballero-Arepa** [comment]
Roger that

**Comment by Caballero-Arepa** [comment]
https://github.com/DW8030/3rd-and-4th-Unique-Component/pull/22

Done

**Comment by Caballero-Arepa** [comment]
Icons still missing tho
