### ISSUE TITLE
Icons and stuffs for VividVale 

### ISSUE THREAD

**Issue by BennieCUBED** [Caballero-Arepa/Community-Civs#104]
Making some icons for VividVale, I'll make some later btw

Star Gazing Spot:

![Untitled5_20230527130314.png](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/3c64034b-668d-4296-a8f2-d8f0c2fba065)

Fire Archer: ![Untitled7_20230611073107.png](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/f852130b-d0f7-4c6f-84c6-ba4e273ae170)

Campsite: ![Untitled8_20230611073842.png](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/e313e8e2-20d1-43ea-80f0-29ac9b21c879)

Also, I would like the campsite to be able to be built without having the city be next to a river tile

I noticed that my fire Archer also has no unique abilities? ![Screenshot_20230611-081337~2.png](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/20390c71-88e6-4508-bcb7-0d70704e40b2)

**Comment by Caballero-Arepa** [comment]
Done
