### ISSUE TITLE
The Free State of New Prussia

### ISSUE THREAD

**Issue by PrussicAcid** [Caballero-Arepa/Community-Civs#107]
[NP.txt](https://github.com/Caballero-Arepa/Community-Civs/files/11710616/NP.txt)
![NP Icon](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/7ff84b2e-f8e6-4628-862d-a767417f07e2)
![Konskript](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/14683977-16ac-49f0-b662-8901888a993e)
![Hirudinea](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/20522b60-d75f-4464-bcf1-6e4c5e347b17)
![Konskript Icon](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/941f10fa-abca-4a12-86f9-a4eaaf1142bc)
![Hirudinea Icon](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/16845242-dffa-494a-a454-cb9313d4c4b3)

**Comment by PrussicAcid** [comment]
![Proper NP Icon](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/dfbb8322-6af6-453f-b31d-5fbd812345c9)
I uploaded the wrong icon lol

**Comment by PrussicAcid** [comment]
![pixil-frame-0 - 2023-06-10T121813 914](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/1433e1ae-e04e-4340-a379-021fec30837a)
Once again, wrong one

**Comment by PrussicAcid** [comment]
![pixil-frame-0 - 2023-06-10T132738 262](https://github.com/Caballero-Arepa/Community-Civs/assets/117550675/9acea535-2552-475a-a1c9-7b704efc8e78)

**Comment by Caballero-Arepa** [comment]
Thank you for loading it here, it will be easier for me to incorporate it

**Comment by PrussicAcid** [comment]
"startIntroPart1": "Ashes to Ashes, Dust to Dust. We won't let the legasy of Germania turn to Rust.",
"startIntroPart2": "Even so, Omega has failed. It's time to deside, whether you will krumble or prevail...",
