### ISSUE TITLE
A1y0sh4's civ: Aleksandria

### ISSUE THREAD

**Issue by A1y0sh4** [Caballero-Arepa/Community-Civs#13]
//Nations

{
		"name": "Aleksandria",
		"leaderName": "A1y0sh4",
		"adjective": ["Aleksandrian"],
		"startBias": ["Tundra"],
		"preferredVictoryType": "Scientific",
	
	        "startIntroPart1": "",
                "startIntroPart2": "",
		
		"declaringWar": "The deeds sing, goddess, of the motherland' son, A1y0sh4, that war enterprises which brought countless glories upon the comrades,\nand sent forth to Hades many valiant enemies, and made them themselves spoil for dogs and every bird.",
		"attacked": "Finally someone ambitious enough to try to win me over. May you succeed or die under my triumph.",
		"defeated": "I know nothing about what I ignore, there's not much that I can do about it,\nand yet my latest realization burns my soul almost as much, in pride, I have burnt till now.",
		"introduction": "Zdravstvuyte! I am A1y0sh4, great emperor of our glorious motherland, but you can call me Alyosha.",
		"neutralHello": "Zdravstvuyte!",
		"hateHello": "I never thought to see you again in this side of the Acheron. What do you want?",
		"tradeRequest": "Some believe that trade is the engine of the world. Would you like to move it in this direction?",
		"favoredReligion": "Christianity",
		"outerColor": [255, 188, 0],
		"innerColor": [255, 255, 255],
		"uniqueName": "The Glory of the Motherland",
		"uniques": ["Empire enters golden age <upon conquering a city>", "[Worker] units gain the [Katorga] promotion"],
		"cities": ["Aleksandriagrad","Nikesburg","Rimgorod","Rodinnesburg","Yekateringrad","Peterinburg","Medvedorod","Ruthensk","Vostgorod",
			"Lyoshasburg","Tovarivsk","Pobedigrad","Aleksisburg","Novaleksandria","Lyoshagrad","Veliksey","kholodnisburg","Veliksandria","Rekasburg",
			"Veragrad","Morozburg"]
	},

//Buildings

      {
		"name": "Kreml'",
            "replaces": "Walls",
		"uniqueTo": "Aleksandria",
		"cityStrength": 8,
		"cityHealth": 50,
            "faith": 1,
		"hurryCostModifier": 25,
		"requiredTech": "Masonry",
		"uniques": ["Destroyed when the city is captured", "[-30]% Culture cost of natural border growth [in this city] <during a Golden Age>"]
	},

//TileImprovements

      {
		"name": "Katorga",
            "uniqueTo": "Aleksandria",
		"terrainsCanBeBuiltOn": ["Strategic resource", "Land"],
		"production": 1,
		"uniques": ["[+1 Production] <in [Tundra] tiles>", "[+1 Production] <in [Snow] tiles>", "[+1 Production] <when below [0] Happiness>", "[+1 Production] <after discovering [Chemistry]>", "Can only be built to improve a resource", "Can be built just outside your borders",
        	"Constructing it will take over the tiles around it and assign them to your closest city", "Removes removable features when built"],
		"shortcutKey": "K"
	},

//UnitPromotions

      {
		"name": "Katorga",
		"uniques": ["Can construct [Katorga] <in [Strategic resource] tiles> <in [Land] tiles>"]
	},

**Comment by Caballero-Arepa** [comment]
![imagen](https://user-images.githubusercontent.com/78449553/219510294-f0f15682-af8d-491d-a33f-29b21c78fe3b.png)

**Comment by A1y0sh4** [comment]
This should be the working version (it fixes katorga, changes a little the UA, and shortens my lines):

//Nations

{
		"name": "Aleksandria",
		"leaderName": "A1y0sh4",
		"adjective": ["Aleksandrian"],
		"startBias": ["Tundra"],
		"preferredVictoryType": "Scientific",
	
	        "startIntroPart1": "",
                "startIntroPart2": "",
		
		"declaringWar": "The deeds sing, goddess, of the Motherland's son, A1y0sh4,\nthat war enterprises which brought countless glories upon the comrades,\nand sent forth to Hades many valiant enemies.",
		"attacked": "Finally someone ambitious enough to try to win me over. May you succeed or die under my triumph.",
		"defeated": "I know nothing about what I ignore, there's not much that I can do about it,\nand yet my latest realization burns my soul almost as much, in pride, I have burnt till now.",
		"introduction": "Zdravstvuyte! I am A1y0sh4, great emperor of our glorious Motherland,\nbut you can call me Alyosha.",
		"neutralHello": "Zdravstvuyte!",
		"hateHello": "I never thought to see you again in this side of the Acheron.\nWhat do you want?",
		"tradeRequest": "Some believe that trade is the engine of the world.\nWould you like to move it in this direction?",
		"favoredReligion": "Christianity",
		"outerColor": [255, 188, 0],
		"innerColor": [255, 255, 255],
		"uniqueName": "Pride of the North",
		"uniques": ["Empire enters golden age <upon conquering a city>", "Free [Worker of the Motherland] appears <upon founding a city> <in [Tundra] tiles>"],
		"cities": ["Aleksandriagrad","Nikesburg","Rimgorod","Rodinnesburg","Yekateringrad","Peterinburg","Medvedorod","Ruthensk","Vostgorod",
			"Lyoshasburg","Tovarivsk","Pobedigrad","Aleksisburg","Novaleksandria","Lyoshagrad","Veliksey","kholodnisburg","Veliksandria","Rekasburg",
			"Veragrad","Morozburg"]
	},

//Buildings

      {
		"name": "Kreml'",
            "replaces": "Walls",
		"uniqueTo": "Aleksandria",
		"cityStrength": 8,
		"cityHealth": 50,
            "faith": 1,
		"hurryCostModifier": 25,
		"requiredTech": "Masonry",
		"uniques": ["Destroyed when the city is captured", "[-30]% Culture cost of natural border growth [in this city] <during a Golden Age>"]
	},

//TileImprovements

      {
		"name": "Katorga",
            "uniqueTo": "Aleksandria",
		"terrainsCanBeBuiltOn": ["Land"],
		"production": 1,
		"uniques": ["Great Improvement", "[+1 Production] <in [Tundra] tiles>", "[+1 Production] <in [Snow] tiles>", "[+1 Production] <when below [0] Happiness>", "[+1 Production] <after discovering [Chemistry]>", "Constructing it will take over the tiles around it and assign them to your closest city", "Removes removable features when built"],
		"shortcutKey": "K"
	},

//Units

{
		"name": "Worker of the Motherland",
            "replaces": "Worker",
		"uniqueTo": "Aleksandria",
		"unitType": "Civilian",
		"movement": 2,
		"uniques": ["Can build [Land] improvements on tiles", "Can construct [Katorga] <in [Strategic resource] tiles>"],
		"cost": 70
},

**Comment by A1y0sh4** [comment]
And here should be the IconFiles:
![Aleksandria](https://user-images.githubusercontent.com/102094544/219874316-c958c9e7-e095-4f20-92fb-f8f45cda352e.png)
![Katorga](https://user-images.githubusercontent.com/102094544/219874325-67c52377-f6ee-41b4-b518-ea4ce6542e12.png)
![Kreml'](https://user-images.githubusercontent.com/102094544/219874345-684c841d-2b44-4c37-9357-cff369641aa4.png)
![Worker of the Motherland](https://user-images.githubusercontent.com/102094544/219874352-fc4f16d6-3926-4e1c-a779-a7f48a919b15.png)

**Comment by A1y0sh4** [comment]
This should be the definitive version of my civ:

//Nations

{
		"name": "Aleksandria",
		"leaderName": "A1y0sh4",
		"adjective": ["Aleksandrian"],
		"startBias": ["Tundra"],
		"preferredVictoryType": "Scientific",
	
	        "startIntroPart1": "",
                "startIntroPart2": "",
		
		"declaringWar": "The deeds sing, goddess, of the Motherland's son, A1y0sh4,\nthat war enterprises which brought countless glories upon the comrades,\nand sent forth to Hades many valiant enemies.",
		"attacked": "Finally someone ambitious enough to try to win me over.\nMay you succeed or die under my triumph.",
		"defeated": "I know nothing about what I ignore, there's not much that I can do about it,\nand yet my latest realization burns my soul almost as much, in pride, I have burnt till now.",
		"introduction": "Zdravstvuyte! I am A1y0sh4, great emperor of our glorious Motherland,\nbut you can call me Alyosha.",
		"neutralHello": "Zdravstvuyte!",
		"hateHello": "Are you still in this side of the Acheron?\nWhat do you want?",
		"tradeRequest": "Some believe that trade is the engine of the world.\nWould you like to move it in this direction?",
		"favoredReligion": "Christianity",
		"outerColor": [255, 188, 0],
		"innerColor": [255, 255, 255],
		"uniqueName": "Pride of the North",
		"uniques": ["Empire enters golden age <upon conquering a city>", "Free [Worker] appears <upon founding a city> <in [Tundra] tiles>"],
		"cities": ["Aleksandriagrad","Nikesburg","Rimgorod","Rodinnesburg","Yekateringrad","Peterinburg","Medvedorod","Ruthensk","Vostgorod",
			"Lyoshasburg","Tovarivsk","Pobedigrad","Aleksisburg","Novaleksandria","Lyoshagrad","Veliksey","kholodnisburg","Veliksandria","Rekasburg",
			"Veragrad","Morozburg"]
	},

//Buildings

      {
		"name": "Kreml'",
            "replaces": "Walls",
		"uniqueTo": "Aleksandria",
		"cityStrength": 8,
		"cityHealth": 50,
            "faith": 1,
		"hurryCostModifier": 25,
		"requiredTech": "Masonry",
		"uniques": ["Destroyed when the city is captured", "[-30]% Culture cost of natural border growth [in this city] <during a Golden Age>"]
	},

//TileImprovements

      {
"name": "Katorga",
"uniqueTo": "Aleksandria",
"terrainsCanBeBuiltOn": ["Snow", "Tundra", "Hill", "Forest"],
"production": 1,
"turnsToBuild": 5,
"uniques": ["Great Improvement", "Can only be built on [Strategic resource] tiles", "[+1 Production] <after discovering [Chemistry]>", "[+1 Production] <when below [0] Happiness>", "Constructing it will take over the tiles around it and assign them to your closest city"],
"techRequired": "Metallurgy",
"shortcutKey": "K"
      }
      
//Icons      
      
-Kreml' Icon:
      
![Kreml'](https://user-images.githubusercontent.com/102094544/219978439-a8258ea2-1466-4641-8bf3-a75da15e9021.png)

-TileSets/HexaRealm/Tiles/Katorga:

![Katorga HexaRealm](https://user-images.githubusercontent.com/102094544/219978546-282b3c64-4f3b-49dd-8650-e1537c3dc372.png)

-TileSets/FantasyHex/Tiles/Katorga:

![Katorga FantasyHex](https://user-images.githubusercontent.com/102094544/219978615-35878455-fdca-4da8-a4a4-bdb0110fd609.png)
