### ISSUE TITLE
New City styles for VividVale.

### ISSUE THREAD

**Issue by BennieCUBED** [Caballero-Arepa/Community-Civs#140]
![City center-Ancient era-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/f572ae2e-371c-4d32-bec0-45a8cbd3671f)

![City center-Classical era-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/81fbb8c3-389d-4adf-9aa6-236b631de5eb)

![City center-Medieval era-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/5163f097-3224-4c4f-81e8-e6944b1388d4)

![City center-Renaissance era-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/2f84f73b-cc9d-44f1-b3b4-73b2e817f901)

![City center-Industrial era-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/2de0c0e0-ae79-472c-bf9a-61d7ec3cd476)

**Comment by Caballero-Arepa** [comment]
Done, will enter next update
