### ISSUE TITLE
HexaRealm style, VividVale

### ISSUE THREAD

**Issue by BennieCUBED** [Caballero-Arepa/Community-Civs#155]
Seeing that Arepa had made some unique images for HexaRealm, I decided to make some too.

![Gatling Gun-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/ab430f40-a477-4919-8bdd-eed59a0413f6)
![Great War Infantry-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/e2f02a60-4d11-4ab8-8875-cdcf1882b777)
![Worker-VividValean-Modern era](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/bf832878-3261-4575-b622-56f6bb5d06b9)
![Pikeman-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/5a0cd4a3-ee9a-4c84-bd63-12a7ecc02140)
![Worker-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/b6a0201f-6698-463f-9cd7-8cccd8f63567)
![Swordsman-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/77ad2af0-6a56-4102-89a6-a2f8ff27dc10)
![Warrior-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/b13df691-06dd-4dc4-9964-715243bf7434)
![Settler-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/54b996c4-eb47-4c6a-b74d-6ab7ff0dc91e)
![Crossbowman-VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/93e597fd-d6b8-4f8c-9b29-91f7ea35895b)
![Rifleman - VividValean](https://github.com/Caballero-Arepa/Community-Civs/assets/127475018/81807292-999b-4108-ad28-c4fb33eb84c7)

**Comment by Caballero-Arepa** [comment]
Very nice!
