### ISSUE TITLE
I'm just giving idea

### ISSUE THREAD

**Issue by Justamodderkid** [Caballero-Arepa/Community-Civs#160]
I just wanna have my nation

//nations
		"name": "Nukaruzania",
		"leaderName": "Nurasanana III",
		"adjective": ["Nukaranian"],
		"startBias": ["plains"],
		"preferredVictoryType": "Domination",
		"personality": "Nukaranian III",

		"startIntroPart1": "welcome back the great leader, Nurasanana third. Welcome back to your great nation. From east China to Nepal you're leading your 2.800,000 population from small country to big country in 789 BC. Your country journey start on 2389 BC and ends on 678 BC after 3 leader after you pass away. 
		"startIntroPart2": "The Great Nurasanana third, your nation memory still lives through you and your people. Will you create a spark to enlighten the world again? Will your new empire shine through the ages of history?",

		"declaringWar": "Oh your trial peace with me has end, prepare for blood fall. ",
		"attacked": "Goodbye, trial friend.",
		"defeated": "oh... Thanks to play with me, goodbye...",
		"introduction": "You? Oh hi my tr- oh I mean friends!",

		"neutralHello": "Toroejo.(hi in nurra Language)",
		"hateHello": "Hi.",

		"tradeRequest": "[Give trade] En- I mean my Comrades, let's do a deal please. [Counteroffensive] think this kamerad. "
		"outerColor": [29,83,63],
		"innerColor": [213,949,,
		"favoredReligion": "Islam",
		"uniqueName": "Nuro democracy",
		"uniques":+300% Unit power vs [conquered city],-25% policies cost when peace,get free [Great artist] from each 7 city,+20% happiness when Civ is not on war",
		"cities": ["Ancient Nuras","Akkadia","Nuras","Gacata","Borkura","Martis","Opis","Mari","Shushan","wEshnunna"," Dafvu"
			"New Nuras","Erech","Kutahar","Batam","Surabayay","Ashur-akabu","Ninveh","Nimrud","Arabela","Nutai",
			"Zabrud","Berlian","Uran"," Tiong","Mashkan Shapir","Tuttul","Ramad","Ana","Haradum","Agrab",
			"Uqair","Gubba","Hafriyat","Nagar","Shubat Enlil","Urhai","Urkesh","Awan", 
-Unit
* Independence warriors [settlers logo with leave]
(Type:sword) Need physiology tech. 
Traits:+300% power vs [conquered city]
Production cost:100
* Democracies Spreader [missionary logo with a leave] (type:civil) need civil service tech. 
Traits:can build Civil Statue (Death) 
Production cost:450
-Building
* Civil Statue [Statue icon]
Only can builded by [Democracies Spreader]
+3 Culture and +4 Food
* Hero Statue [Shrine icon]
Need Civil service tech. (Need sacrifice a unit on completion) +3 Culture +10 Xp to a Unit trained in this city
Production cost:70

I just give a idea okay? You also can give a chance.thanks.

**Comment by Caballero-Arepa** [comment]
Hi!
Very nice that you want to have your own civ here.
I believe the concept is interesting, but there are a few issues:
- What do you mean by "Conquered city"?
- What "psychology" tech?
- We have to heavily nerf it, your civ is very very OP.
   We make balanced civs

**Comment by Justamodderkid** [comment]
Oh sorry Conquered City is like
Example: The capital has been [conquered] = 300�
Power to attack the city

Psychology tech? I'm just wrong typing philosophy

Nerf? You can nerf by yourself I don't know what nerf I can do but you can
decide it!

Pada Sen, 22 Jul 2024, 07.25, Caballero Arepa ***@***.***>
menulis:

**Comment by Justamodderkid** [comment]
Conquered city is like
Example(revamp) :Enemy Unit {warrior} (Carthage) has conquered Ancient
Nuras, +120% power (nerf from 300%) to unit to attack the city


Nerf:-10% (From 25%) policies cost if First Great Artist spawn (nerf if
this auto get)

For every each 15 City (from 7) you can select Great Artist or 9 Round
golden age (revamp)

Pada Sen, 22 Jul 2024, 21.21, Marvel Asthon ***@***.***>
menulis:

**Comment by Caballero-Arepa** [comment]
Ah, I see what you mean now. Very good!
I'll code it in when I can, no problem

**Comment by Justamodderkid** [comment]
![Tak berjudul2_20240726185701](https://github.com/user-attachments/assets/12bf6682-07fe-4f03-908a-7032b335336b)
![Tak berjudul1_20240726185505](https://github.com/user-attachments/assets/d976b696-70c9-497b-afc4-5cd9555684b0)

Idk it's work or not but I make a Image for my Nation, The sword one is Independence warriors icon and the Broken Image is The Nation Icon.
