### ISSUE TITLE
VividVale: Icons

### ISSUE THREAD

**Issue by BennieCUBED** [Caballero-Arepa/Community-Civs#87]
Civ icon:
![Untitled3_20230316071308](https://user-images.githubusercontent.com/127475018/225447594-7aab5f3e-8ef6-4ef1-aa83-b479be072596.png)
Unit Icon: 
![Untitled4_20230316072235](https://user-images.githubusercontent.com/127475018/225447682-873c8d96-884a-44bc-b52e-0c4072ea3e9b.png)

**Comment by BennieCUBED** [comment]
There colour might have to be white, you could just probably change this yourself, sorry

**Comment by Caballero-Arepa** [comment]
Alright, thank you, but holy moly, those are a very big icons. Standart icon sizes are 200x200px.

I already sized them down, and changed colors, but have it in mind for the future.

Btw, all icons should be white, with the only exception of building icons, which those are truly black.
