### ISSUE TITLE
Changing some things for VividVale

### ISSUE THREAD

**Issue by BennieCUBED** [Caballero-Arepa/Community-Civs#93]
I want to replace the Community Market unique building with a new unique building:

 Campsite, Replaces Garden. 1+ Production from Bonus resource tiles in this city

"startIntroPart1": "The people of VividVale learned to thrive on the coast with many neighbouring cultures to learn, and yet some want to destroy those cultures, but you have the power to protect their cultures",

        "startIntroPart2": "can you protect cultures?
Can you create a civilisation that can stand the test of time?",

        "tradeRequest": " Want to make a deal?",

Thanks

**Comment by BennieCUBED** [comment]
Hang on, I'll add more thing shortly

**Comment by Caballero-Arepa** [comment]
Alr, I'll do it when I have time.

Except the unit sprites, I dont do sprites for other people as I have more things to do

**Comment by BennieCUBED** [comment]
Ye alr
